// AUTO-GENERATED by scripts/refresh-official-urban-data.mjs before dev/build.
// The checked-in empty snapshot is intentional: builds must refresh from the
// official public APIs rather than silently falling back to invented values.

export type OfficialAreaUrbanData = {
  analysisAreaM2: number;
  observedTreeCanopy2018: number;
  observedVegetation2018: number;
  observedUhi2018: number;
  nonVegetatedSurfaceProxy: number;
  treeInventory2025: {
    count: number;
    youngShare: number;
    matureShare: number;
    oldShare: number;
    atRiskShare: number;
    averageDbhCm: number | null;
  };
  buildings2023: {
    structureCount: number;
    buildingCoverage: number;
    averageHeightM: number | null;
  };
  coverageNote: string;
};

export const officialUrbanData: Record<string, OfficialAreaUrbanData> = {};

export const officialDataProvenance = {
  generatedAt: null as string | null,
  treeInventory: {
    organisation: "City of Melbourne",
    dataset: "Trees, with species and dimensions (Urban Forest)",
    sourceYear: 2025,
    resourceId: "0f2a2180-2be0-5a58-a270-7538c35259e6",
  },
  buildings: {
    organisation: "City of Melbourne",
    dataset: "2023 Building Footprints",
    sourceYear: 2023,
    resourceId: "5826dcef-6524-4099-bdf7-c33e1e372acd",
  },
  urbanHeat: {
    organisation: "Victorian Department of Transport and Planning",
    dataset: "Cooling & Greening — Urban Heat (2018)(MMB)",
    sourceYear: 2018,
    layer: 55,
  },
} as const;
